on:
  push:

name: Build Library

jobs:
  build:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install requirements
        run: |
            sudo apt-get update
            sudo apt-get install wget unzip
            npm install --no-save svg2mxlibrary
      - name: Download AREI symbols
        run: |
            wget -O arei.zip https://www.shadowhunter.co.uk/en/download.php?id=en_arei_visio_svg_autocad_elmt.zip
            unzip arei.zip
            ls -la
